<a href="https://colab.research.google.com/github/joedone1/HiLab.internship/blob/master/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def shift_array(array, shift_direction, shift_index, num_elements):
    """
    This function shifts the elements of a 2D array in any of the four directions: up, down, left, or right.

    :param array: 2D numpy array to be shifted
    :param shift_direction: string, 'row' or 'column' indicating the direction of the shift
    :param shift_index: integer, the index of the row or column to be shifted
    :param num_elements: integer, the number of elements to be shifted
    :return: 2D numpy array with the shifted elements
    """

    if shift_direction == 'row':
        return np.concatenate((array[shift_index+1:, :], array[shift_index:shift_index+1, :]), axis=0)
    elif shift_direction == 'column':
        return np.concatenate((array[:, shift_index+1:], array[:, shift_index:shift_index+1]), axis=1)
    else:
        raise ValueError("shift_direction should be either 'row' or 'column'")

# Testing the function
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

shifted_arr = shift_array(arr, 'row', 1, 2)
print(shifted_arr)

shifted_arr = shift_array(arr, 'column', 1, 2)
print(shifted_arr)

[[7 8 9]
 [4 5 6]]
[[3 2]
 [6 5]
 [9 8]]


In [2]:
def shift_list(input_list, index):
    """
    This function splits a list by an index, then cuts the list from that index and attaches the right part to the beginning of the list.

    :param input_list: list to be shifted
    :param index: integer, the index at which to split the list
    :return: list with the shifted elements
    """

    left_part = input_list[:index]
    right_part = input_list[index:]

    shifted_list = right_part + left_part

    return shifted_list

# Testing the function
my_list = [1, 2, 3, 4, 5, 6, 7]
index = 4

shifted_list = shift_list(my_list, index)
print(shifted_list)

[5, 6, 7, 1, 2, 3, 4]
